### ISSUE TITLE
The popular book image is not shown in the website

### ISSUE THREAD

**Issue by namunakc** [PramodChaudhary10/LibraryManagementSystem#10]
![IMG-6d4d29eb65c627dcd24fde92f1f1b7f9-V](https://user-images.githubusercontent.com/81402395/114826802-a9666b80-9de7-11eb-8376-1a00a65c02d0.jpg)

**Comment by Bibekshrestha04** [comment]
The images in popular books section  has been  fixed and can be viewed.
![Screenshot 2021-04-16 105046](https://user-images.githubusercontent.com/81401256/114974334-e7c06100-9ea1-11eb-99d8-47316152da22.jpg)
