### ISSUE TITLE
Images not loaded in home page

### ISSUE THREAD

**Issue by PramodChaudhary10** [PramodChaudhary10/LibraryManagementSystem#11]
While running the our project I can detect that in home page images are not loaded properly.
![image](https://user-images.githubusercontent.com/81400957/114992759-d33c9280-9eba-11eb-9828-c9f3af09a2b9.png)

**Comment by Bibekshrestha04** [comment]
The image issue has been solved in the home page.
![Image issue](https://user-images.githubusercontent.com/81401256/115000809-d3d92700-9ec2-11eb-8c41-f3aeffbe5290.png)
