### ISSUE TITLE
Footer is misplace

### ISSUE THREAD

**Issue by Upendra0987** [PramodChaudhary10/LibraryManagementSystem#12]
![image](https://user-images.githubusercontent.com/81401338/118246903-489f8100-b4c2-11eb-9f54-625361eff562.png)

**Comment by PramodChaudhary10** [comment]
Footer problem is solved
![image](https://user-images.githubusercontent.com/81400957/118314334-b9bb5480-b513-11eb-83ed-3e504efd03a3.png)
