### ISSUE TITLE
Title issue

### ISSUE THREAD

**Issue by Upendra0987** [PramodChaudhary10/LibraryManagementSystem#13]
![image](https://user-images.githubusercontent.com/81401338/118247354-d11e2180-b4c2-11eb-8f3d-48515d1fa007.png)

**Comment by nirmaltdr** [comment]
The issue of the page title has been solved and updated.

![Screenshot (177)](https://user-images.githubusercontent.com/81401238/118358009-97214e00-b59c-11eb-9970-4885587e430e.png)
