### ISSUE TITLE
About us Footer misplaced 

### ISSUE THREAD

**Issue by sabina54321** [PramodChaudhary10/LibraryManagementSystem#14]
![image](https://user-images.githubusercontent.com/81378852/118248969-9ddc9200-b4c4-11eb-88c0-a7501764fd20.png)
Please fix the place of footer at the bottom of the page

**Comment by PramodChaudhary10** [comment]
Footer misplaced problem is solved
![image](https://user-images.githubusercontent.com/81400957/118314735-40703180-b514-11eb-8d6a-7242b196fe56.png)
