### ISSUE TITLE
The book image is too big.

### ISSUE THREAD

**Issue by nirmaltdr** [PramodChaudhary10/LibraryManagementSystem#16]
![Screenshot (113)](https://user-images.githubusercontent.com/81401238/118358148-44946180-b59d-11eb-8991-7eb3aac453c6.jpg)

**Comment by Bibekshrestha04** [comment]
Fixed book image size.
![solve](https://user-images.githubusercontent.com/81401256/118353683-27549880-b587-11eb-85fd-a79bb8fa540a.jpg)
