### ISSUE TITLE
The footer is unappealing to look at and need a little fixing. 

### ISSUE THREAD

**Issue by nirmaltdr** [PramodChaudhary10/LibraryManagementSystem#17]
![Screenshot (114)](https://user-images.githubusercontent.com/81401238/118358166-55dd6e00-b59d-11eb-8ada-0eee90eca02c.jpg)

**Comment by Bibekshrestha04** [comment]
Done
![solved 1](https://user-images.githubusercontent.com/81401256/118359184-0d747f00-b5a2-11eb-8732-10ade56084e0.jpg)
