### ISSUE TITLE
Logo not shown in Nav bar

### ISSUE THREAD

**Issue by Bibekshrestha04** [PramodChaudhary10/LibraryManagementSystem#19]
![logo](https://user-images.githubusercontent.com/81401256/118387227-fb93ea00-b63c-11eb-8079-876af1298a78.jpg)

**Comment by namunakc** [comment]
the logo has been added.
![118387227-fb93ea00-b63c-11eb-8079-876af1298a78](https://user-images.githubusercontent.com/81402395/118390953-8ed71a80-b651-11eb-9bfb-e627fea16dea.jpg)
