### ISSUE TITLE
HyperLink not working in section of About.html Page.

### ISSUE THREAD

**Issue by Bibekshrestha04** [PramodChaudhary10/LibraryManagementSystem#4]
While i was testing website i found error while opening About us Page. 

![Screenshot 2021-04-13 140454](https://user-images.githubusercontent.com/81401256/114521440-223bbb00-9c62-11eb-81e0-3d5a4fc6f541.jpg)

![Screenshot 2021-04-13 140327](https://user-images.githubusercontent.com/81401256/114521450-24057e80-9c62-11eb-97d9-5be902fadaaf.jpg)

**Comment by nirmaltdr** [comment]
i have found and solve this issue.
![174393601_1616551225401136_822553824007272458_n](https://user-images.githubusercontent.com/81401238/115008113-777a0580-9eca-11eb-96ec-b03a96ab50c2.png)
![174227797_4181594088572191_5239903342193464715_n](https://user-images.githubusercontent.com/81401238/115008118-78129c00-9eca-11eb-9b6f-352d3f44894b.png)
