### ISSUE TITLE
Model Error

### ISSUE THREAD

**Issue by sabina54321** [PramodChaudhary10/LibraryManagementSystem#6]
when  I hits python manage.py runserver  its occurs model error.
![image](https://user-images.githubusercontent.com/81378852/114531628-cc6c1080-9c6b-11eb-9d0b-cae0aa22bbe9.png)

**Comment by PramodChaudhary10** [comment]
Thank you sabina for your essential issue. I can  fix the error , now it is ready to run.
![image](https://user-images.githubusercontent.com/81400957/114571317-4b763e80-9c96-11eb-9e63-540514391880.png)
![image](https://user-images.githubusercontent.com/81400957/114571340-516c1f80-9c96-11eb-800d-b62b2f3aa837.png)
![Uploading image.png…]()
