### ISSUE TITLE
Login page is not working

### ISSUE THREAD

**Issue by Upendra0987** [PramodChaudhary10/LibraryManagementSystem#8]
![image](https://user-images.githubusercontent.com/81401338/114664510-85d5ef00-9d1b-11eb-9534-c791939aca7f.png)

**Comment by PramodChaudhary10** [comment]
![image](https://user-images.githubusercontent.com/81400957/115007004-3df4ca80-9ec9-11eb-9e42-a60efb3cb754.png)
Now it is working perfectly.
