### ISSUE TITLE
The image is not shown in home page

### ISSUE THREAD

**Issue by nirmaltdr** [PramodChaudhary10/LibraryManagementSystem#9]
![11](https://user-images.githubusercontent.com/81401238/114665614-fa5d5d80-9d1c-11eb-822f-2204eed3bd29.jpg)

**Comment by Bibekshrestha04** [comment]
The image issue has been solved in the home page.

![Screenshot (1)](https://user-images.githubusercontent.com/81401256/114973654-9f547380-9ea0-11eb-9f0f-c5f588863742.png)
